import { internalMutation } from "./_generated/server";
import { v } from "convex/values";

// All accessories data compiled from eKeystone + eTristate + web research
// Sell prices are rounded to simple numbers per Jon's request (±5%)
// Labor rate: $150/hr (Jon confirmed)
const ACCESSORIES = [
  // ═══ FRONT BUMPERS ═══
  { category: "Front Bumpers", brand: "Ranch Hand", series: "Summit", partNumber: "FSF231BL1", cost: 1206, mapPrice: undefined, retailPrice: 2010, sellPrice: 1800, installHours: 3.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQiK9QFvkn_GL57lBeEzCLrSfM_8BfpLtGBx5j7Gy8LlQjmHiDkiOiZ0OkY&s", sortOrder: 1 },
  { category: "Front Bumpers", brand: "Ranch Hand", series: "Legend", partNumber: "FBF231BLR", cost: 1418, mapPrice: undefined, retailPrice: 2363, sellPrice: 2100, installHours: 3.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSBrq4n07vYoF4wDS-fgVnMBnyH2jhFao0RjCYKdcD62ahA-p4u3_ePsde&s", sortOrder: 2 },
  { category: "Front Bumpers", brand: "Ranch Hand", series: "Sport", partNumber: "FBF235BLR", cost: 1658, mapPrice: undefined, retailPrice: 2764, sellPrice: 2500, installHours: 3.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTCTWIrmMsz7b23a2wFcfdcsjeeoTxJazB_aNCrK-UhpxQKkHXjxev343ad&s", sortOrder: 3 },
  { category: "Front Bumpers", brand: "Steelcraft", series: "HD Replacement", partNumber: "HD11390RCC", cost: 1302, mapPrice: undefined, retailPrice: 2170, sellPrice: 1950, installHours: 3.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS-O8L0SO1Tw0pwGf9JcsvkmLdj11K-0RtWu7YyHvbUJ9M5QFZwolNpF0mz&s", sortOrder: 4 },

  // ═══ REAR BUMPERS ═══
  { category: "Rear Bumpers", brand: "Ranch Hand", series: "Legend", partNumber: "BBF231BLSS", cost: 663, mapPrice: undefined, retailPrice: 1105, sellPrice: 1000, installHours: 2.0, source: "eKeystone", notes: "2025 Ford F-350. 2.0hr per labor guide (incl sensors if applicable)", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT43noV-hlLNiybhnUlxdGb9KPFte1NCbW7dMcF1KTvRsOG2ykysofFgQcS&s", sortOrder: 1 },
  { category: "Rear Bumpers", brand: "Ranch Hand", series: "Sport", partNumber: "SBF231BLSL", cost: 683, mapPrice: undefined, retailPrice: 1139, sellPrice: 1000, installHours: 2.0, source: "eKeystone", notes: "2025 Ford F-350. 2.0hr per labor guide (incl sensors if applicable)", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTV9UxC8bV1KLJu0rwVBq_TEIq9W27mqSytuneixAmIeBovM_a1ryVeMUKh&s", sortOrder: 2 },

  // ═══ GRILLE GUARDS ═══
  { category: "Grille Guards", brand: "Ranch Hand", series: "Legend", partNumber: "GGF231BL1", cost: 677, mapPrice: undefined, retailPrice: 1128, sellPrice: 1000, installHours: 2.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRZD-tq8TVNtZsv0zLXverOGfJqJmF4AB0DlgW8HIYf5scyJiaVnOUWeAhe&s", sortOrder: 1 },
  { category: "Grille Guards", brand: "Steelcraft", series: "HD", partNumber: "50-1390C", cost: 617, mapPrice: undefined, retailPrice: 1028, sellPrice: 900, installHours: 2.0, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRv3V3bdC0jhYN2fuf1GcYX-QIFyJGNZT1gLeBCHJ-OS-Vu6hIqJxlNa3zt&s", sortOrder: 2 },

  // ═══ B&W GOOSENECK HITCHES ═══
  { category: "Gooseneck Hitches", brand: "B&W", series: "Turnoverball Full Kit", partNumber: "GNRK1123", cost: 470, mapPrice: 699, retailPrice: 836, sellPrice: 700, installHours: 4.0, source: "eTristate", notes: "Ford bolt-on, no drill. 4.0hr w/ 7-way plug per labor guide", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRxVWeaTJbWf5Vnj_jwFcIMcLrehg0MefeudMKbJP7JfnmvQDylY1QZa4RTjnx2ctug8YvIIqWx8iPGfx1s_gIb0oHPi4jqpAa-9h3TUrM1vpN-ZtLDD1J6EuQBeKTyXk9L1AzkUkmt6g&usqp=CAc", sortOrder: 1 },
  { category: "Gooseneck Hitches", brand: "B&W", series: "Mounting Kit Only", partNumber: "GNRM1123", cost: 203, mapPrice: 300, retailPrice: 360, sellPrice: 300, installHours: 4.0, source: "eTristate", notes: "Needs center assembly. 4.0hr w/ 7-way plug per labor guide", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRxVWeaTJbWf5Vnj_jwFcIMcLrehg0MefeudMKbJP7JfnmvQDylY1QZa4RTjnx2ctug8YvIIqWx8iPGfx1s_gIb0oHPi4jqpAa-9h3TUrM1vpN-ZtLDD1J6EuQBeKTyXk9L1AzkUkmt6g&usqp=CAc", sortOrder: 2 },

  // ═══ B&W TOW & STOW ═══
  { category: "Tow & Stow Hitches", brand: "B&W", series: "2\" Shank, Dual Ball, 5\" Drop", partNumber: "TS10037B", cost: 196, mapPrice: 269, retailPrice: 334, sellPrice: 275, installHours: undefined, source: "eTristate", notes: "Customer self-install", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcRxVWeaTJbWf5Vnj_jwFcIMcLrehg0MefeudMKbJP7JfnmvQDylY1QZa4RTjnx2ctug8YvIIqWx8iPGfx1s_gIb0oHPi4jqpAa-9h3TUrM1vpN-ZtLDD1J6EuQBeKTyXk9L1AzkUkmt6g&usqp=CAc", sortOrder: 1 },
  { category: "Tow & Stow Hitches", brand: "B&W", series: "2\" Shank, Dual Ball, 7\" Drop", partNumber: "TS10040B", cost: 218, mapPrice: 299, retailPrice: 372, sellPrice: 300, installHours: undefined, source: "eTristate", notes: "Customer self-install", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcS3U1pVn-zeluG16F1C2bGNHfxvqNGGAdE4ZOyaY-9MTr4fdqR41GTrFBhGOziVQbE0D4BaJr5m-78wO2VhiBb7VLjBlzbHp2UDdbe0dyortzOyT2lMaAihdw&usqp=CAc", sortOrder: 2 },
  { category: "Tow & Stow Hitches", brand: "B&W", series: "2.5\" Shank, Dual Ball, 5\" Drop", partNumber: "TS20037B", cost: 225, mapPrice: 309, retailPrice: 384, sellPrice: 325, installHours: undefined, source: "eTristate", notes: "Customer self-install", imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcQo3b7vREkrzTKe3a26R10u3cm6KDQAh11BZ0mNsM5NBhRvM2MSMBJwMQEcvZBgAn5FTPgtMJa5fDhMZuT8TL-8vO5WAIWawAm9DtO0ApE1&usqp=CAc", sortOrder: 3 },
  { category: "Tow & Stow Hitches", brand: "B&W", series: "2.5\" Shank, Dual Ball, 7\" Drop", partNumber: "TS20040B", cost: 255, mapPrice: 349, retailPrice: 434, sellPrice: 350, installHours: undefined, source: "eTristate", notes: "Customer self-install", imageUrl: "https://encrypted-tbn3.gstatic.com/shopping?q=tbn:ANd9GcRzViJYZTKq2oTfzxh-r864OGrKMj_l1I4GCUJid5dctNitTKTPSQrlxTby3c-Zd7n13Z-7KpRoK94ieKMx4QlDRwLykTXxj7yX6WQIZ9o-PnHX8FftIAoUrg&usqp=CAc", sortOrder: 4 },

  // ═══ RUNNING BOARDS / STEPS ═══
  { category: "Steps & Running Boards", brand: "LUVERNE", series: "Grip Step 7\"×36\" w/ Brackets", partNumber: "415036", cost: 348, mapPrice: 464, retailPrice: 500, sellPrice: 475, installHours: 1.5, source: "eTristate", notes: "Includes vehicle-specific mounting brackets", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUDC73wVn0AoVdWOW4_PFC26kLu5m5YQmPL6QZZgGFZFKP9B7YwwodMC3A&s", sortOrder: 1 },
  { category: "Steps & Running Boards", brand: "LUVERNE", series: "Grip Step 7\"×60\" w/ Brackets", partNumber: "415060", cost: 387, mapPrice: 515, retailPrice: 558, sellPrice: 525, installHours: 1.5, source: "eTristate", notes: "Includes vehicle-specific mounting brackets", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQr2jq_SdLx_MF5qwyFBBy9BB3XZFItj-WRsv3buLDPpZPPMQZAQGW8fvQj&s", sortOrder: 2 },
  { category: "Steps & Running Boards", brand: "LUVERNE", series: "O-Mega II 6\"×100\" w/ Brackets", partNumber: "584100", cost: 395, mapPrice: 534, retailPrice: 607, sellPrice: 575, installHours: 1.5, source: "eTristate", notes: "Black aluminum, includes vehicle-specific mounting brackets", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFk4k0QGVxwsR0xJ6jz3r8xyVfgVdirDgczDqzOWyYvb1VeHQAQ0C-hGXK&s", sortOrder: 3 },
  { category: "Steps & Running Boards", brand: "LUVERNE", series: "O-Mega II 6\"×114\" w/ Brackets", partNumber: "584114", cost: 511, mapPrice: 644, retailPrice: 732, sellPrice: 675, installHours: 1.5, source: "eTristate", notes: "Black aluminum, includes vehicle-specific mounting brackets", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSFk4k0QGVxwsR0xJ6jz3r8xyVfgVdirDgczDqzOWyYvb1VeHQAQ0C-hGXK&s", sortOrder: 4 },
  { category: "Steps & Running Boards", brand: "AMP Research", series: "PowerStep PnP", partNumber: "76254-01A", cost: 1386, mapPrice: 1800, retailPrice: 2700, sellPrice: 1800, installHours: 2.5, source: "eTristate", notes: "Chevy/GMC — Ford PN pending", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT5eJggsa43XVFYdcdz93833KY3Xrv1GYlc0SyS8fiOrw-VwoA3_JcNYSM2&s", sortOrder: 5 },
  { category: "Steps & Running Boards", brand: "AMP Research", series: "BedStep (Frame Mount)", partNumber: "75330-01A", cost: 254, mapPrice: undefined, retailPrice: 423, sellPrice: 400, installHours: 0.5, source: "eKeystone", notes: "2025 Ford F-350", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQt9JBdUrTiOSGDaYYEnNh8DAsCYVy5FalVUiC5OLcAEeKtz_Loys4OSVWK&s", sortOrder: 6 },
  { category: "Steps & Running Boards", brand: "Ranch Hand", series: "Legend Cab-Length Steps", partNumber: "RSF171C8B4", cost: 475, mapPrice: undefined, retailPrice: 735, sellPrice: 700, installHours: 1.5, source: "Web", notes: "3\" pipe, 3/16\" brackets — vehicle-specific", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbKcFvX3ioJd0sREF7z7PxpxGHzM2bIQqy7YUEFKdpHqD6S-F9AJLv4lXm&s", sortOrder: 7 },
  { category: "Steps & Running Boards", brand: "Ranch Hand", series: "Legend Wheel-to-Wheel Steps", partNumber: "RSF171E8B6", cost: 550, mapPrice: undefined, retailPrice: 863, sellPrice: 825, installHours: 1.5, source: "Web", notes: "3\" pipe, extends to bed access — vehicle-specific", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbKcFvX3ioJd0sREF7z7PxpxGHzM2bIQqy7YUEFKdpHqD6S-F9AJLv4lXm&s", sortOrder: 8 },
  { category: "Steps & Running Boards", brand: "Generic", series: "4\" Round Black Tube Steps", partNumber: "NB-4RD-BLK", cost: 100, mapPrice: undefined, retailPrice: 250, sellPrice: 200, installHours: 1.5, source: "Web", notes: "Black powder-coated steel, includes brackets", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDRaVdvN97z8FjBYMxD7HqVfDmmBn0CjH8BJ3k_cEBiKdDdOQKS0kGzF8l&s", sortOrder: 9 },

  // ═══ TOOLBOXES ═══
  { category: "Toolboxes", brand: "UWS", series: "69\" Crossover (Bright Alum)", partNumber: "TBS-69", cost: 361, mapPrice: 634, retailPrice: 698, sellPrice: 650, installHours: 1.0, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShJF3rr2yUXfgfYubvQrRM_2njWek1IimpPwuy70IPUyddSSMI_SGlPhfi&s", sortOrder: 1 },
  { category: "Toolboxes", brand: "UWS", series: "63\" Crossover (Bright Alum)", partNumber: "TBS-63", cost: 361, mapPrice: 632, retailPrice: 696, sellPrice: 650, installHours: 1.0, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcTMHbZEiEvuJsXnHYtqx1pSr8Nyy0apz0DmWWgX30-sWlSBSDOJpKpcwSoNvQcMrqCiDYM96lIvLUKOLAgyU3GNmBQgikGACC2OtmKnm1IStFBjoE_87ZXjaPn0PXIT68zAjdiCCAENTA&usqp=CAc", sortOrder: 2 },
  { category: "Toolboxes", brand: "UWS", series: "69\" Angled Low-Profile", partNumber: "TBS-69-A-LP", cost: 361, mapPrice: 634, retailPrice: 698, sellPrice: 650, installHours: 1.0, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRlP7haJ0hrwocv9hCH9ubkGugHrv1KvC7dtUyX1AmMo5wjM1XrRCCFi1TA&s", sortOrder: 3 },
  { category: "Toolboxes", brand: "Weather Guard", series: "Saddle Box Full Standard", partNumber: "127-0-02", cost: 752, mapPrice: 770, retailPrice: 1052, sellPrice: 800, installHours: 1.0, source: "eTristate", notes: undefined, imageUrl: "https://www.weatherguard.com/getattachment/Products/Tool-Boxes/Truck-Tool-Boxes/Saddle-Box/127-0-02.png", sortOrder: 4 },
  { category: "Toolboxes", brand: "Dee Zee", series: "Red Label Crossover", partNumber: "DZ8170", cost: 373, mapPrice: undefined, retailPrice: 843, sellPrice: 600, installHours: 1.0, source: "eTristate", notes: "Brite-Tread aluminum", imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQcfrLzv0h_OoHoOa7wrvrzB__QChck6RiVR3AEa2-tGZzzcVaYsoaiiEdT-e6vH_tqeOxkur2PvUSSAIs1UG01wcVI7l5OcJUFHbaJtWlEtONp50Rnelx9RncNr26_Brk2TtGSS3Y&usqp=CAc", sortOrder: 5 },
  { category: "Toolboxes", brand: "RKI", series: "Crossbox (Aluminum, Black)", partNumber: "C63AB", cost: 896, mapPrice: undefined, retailPrice: 1582, sellPrice: 1400, installHours: 1.0, source: "eTristate", notes: "Full-size trucks", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShJF3rr2yUXfgfYubvQrRM_2njWek1IimpPwuy70IPUyddSSMI_SGlPhfi&s", sortOrder: 6 },
  { category: "Toolboxes", brand: "RKI", series: "Chest Box (Aluminum, 8ft bed)", partNumber: "MTB60-1NMA", cost: 952, mapPrice: undefined, retailPrice: 1682, sellPrice: 1500, installHours: 1.0, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcShJF3rr2yUXfgfYubvQrRM_2njWek1IimpPwuy70IPUyddSSMI_SGlPhfi&s", sortOrder: 7 },
  { category: "Toolboxes", brand: "Buyers", series: "18×18×24 Underbody (Steel)", partNumber: "1702100", cost: 216, mapPrice: undefined, retailPrice: 461, sellPrice: 350, installHours: 1.0, source: "eTristate", notes: "24\" underbody box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQmMN0BptNHMwCPHvAV2Nsd2pj3K8gjaktZaR5rYjhCdJ6_Ocpd9gb88X0y&s", sortOrder: 8 },
  { category: "Toolboxes", brand: "Buyers", series: "18×18×30 Underbody (Steel)", partNumber: "1702103", cost: 240, mapPrice: undefined, retailPrice: 510, sellPrice: 385, installHours: 1.0, source: "Web", notes: "30\" underbody box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTKtOZlH7cbiSlMGFgiP5i4kNxp2I80uNISphJf95cCmOu5Xd4Ku_WlGMOe&s", sortOrder: 9 },
  { category: "Toolboxes", brand: "Buyers", series: "18×18×36 Underbody (Steel)", partNumber: "1702105", cost: 265, mapPrice: undefined, retailPrice: 565, sellPrice: 425, installHours: 1.0, source: "Web", notes: "36\" underbody box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTZjMmTjXl7vZcTn59R6Fxpsos8KjM2rPelJQnf6vcw9oj6AIpo9MHPDcdI&s", sortOrder: 10 },
  { category: "Toolboxes", brand: "Buyers", series: "18×18×48 Underbody (Steel)", partNumber: "1702110", cost: 310, mapPrice: undefined, retailPrice: 660, sellPrice: 500, installHours: 1.0, source: "Web", notes: "48\" underbody box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSISWU88Wwymr181KYV3HDmz8r06tm3aVkwV1S_mwf0m1Gq9BJjvQKJ5ID3&s", sortOrder: 11 },
  { category: "Toolboxes", brand: "RKI", series: "Floor Drawer 40×10×24", partNumber: "FD401024", cost: 968, mapPrice: undefined, retailPrice: 1710, sellPrice: 1500, installHours: 1.5, source: "eTristate", notes: "White or Black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTxIDVwLQ4c_8kXJdnPWmccLwIf5VEmE3_Sqob0T07na1vmpU2IqQI68Clo&s", sortOrder: 12 },
  // BCI Toolboxes (dealer pricing TBD)
  { category: "Toolboxes", brand: "BCI", series: "TB10 — 10\" Standard Toolbox", partNumber: "BCI-TB10", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/BCI-TB.jpg", sortOrder: 13 },
  { category: "Toolboxes", brand: "BCI", series: "TB13 — 13\" Standard Toolbox", partNumber: "BCI-TB13", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/BCI-TB.jpg", sortOrder: 14 },
  { category: "Toolboxes", brand: "BCI", series: "TB18 — 18\" Standard Toolbox", partNumber: "BCI-TB18", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/BCI-TB.jpg", sortOrder: 15 },
  { category: "Toolboxes", brand: "BCI", series: "TB18-48 — 18\" Narrow (48\" Wide)", partNumber: "BCI-TB18-48", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/BCI-TB.jpg", sortOrder: 16 },
  { category: "Toolboxes", brand: "BCI", series: "SB3 — Small Sidebox", partNumber: "BCI-SB3", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Sidebox/underbody. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_d57dc9ce9aa84408bbf506c108ae4ba7~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/SB3.jpg", sortOrder: 17 },
  { category: "Toolboxes", brand: "BCI", series: "SB4 — Medium Sidebox", partNumber: "BCI-SB4", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Sidebox/underbody. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_6b2a49c5909e4423963ece9b584896c3~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/SB4.jpg", sortOrder: 18 },
  { category: "Toolboxes", brand: "BCI", series: "SB5 — Large Sidebox w/ Bedrail Mount", partNumber: "BCI-SB5", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Bedrail mounting system. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_ac14e12937454760b1ab35a4badfc022~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/SB5.jpg", sortOrder: 19 },
  { category: "Toolboxes", brand: "BCI", series: "SSB5 — Stainless Sidebox", partNumber: "BCI-SSB5", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 1.0, source: "Web", notes: "12ga steel, polyurea coated. Stainless finish. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_f3a8d644c8b645faa9489fcb8f493469~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/SSB5.jpg", sortOrder: 20 },

  // ═══ SIDE PACKS (George's suggestion) ═══
  { category: "Side Packs", brand: "Weather Guard", series: "Topside Box 60\"", partNumber: "174-0-02", cost: 500, mapPrice: undefined, retailPrice: 850, sellPrice: 750, installHours: 1.0, source: "Web", notes: "Aluminum, white", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG1YSJNiMVWNVYn7xPwjyA8_NcAfVL4EyC1GBtlvAWJoydyXW_q7U4bTsZ&s", sortOrder: 1 },
  { category: "Side Packs", brand: "Weather Guard", series: "Lo-Side Box 47\"", partNumber: "174-6-01", cost: 400, mapPrice: undefined, retailPrice: 700, sellPrice: 600, installHours: 1.0, source: "Web", notes: "Low-profile aluminum, gloss black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTG1YSJNiMVWNVYn7xPwjyA8_NcAfVL4EyC1GBtlvAWJoydyXW_q7U4bTsZ&s", sortOrder: 2 },
  { category: "Side Packs", brand: "RKI", series: "Side Pack 60\" Steel", partNumber: "SP60S", cost: 450, mapPrice: undefined, retailPrice: 800, sellPrice: 700, installHours: 1.0, source: "Web", notes: "60\" steel side mount box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMmZsEgzQWU4U87fTSLJ5_xVy0Yw6OGuo2J8Du_DKDWYyemhLuxzFLOCxo&s", sortOrder: 3 },
  { category: "Side Packs", brand: "RKI", series: "Side Pack 48\" Steel", partNumber: "SP48S", cost: 380, mapPrice: undefined, retailPrice: 675, sellPrice: 600, installHours: 1.0, source: "Web", notes: "48\" steel side mount box", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMmZsEgzQWU4U87fTSLJ5_xVy0Yw6OGuo2J8Du_DKDWYyemhLuxzFLOCxo&s", sortOrder: 4 },

  // ═══ SADDLE BOXES (George's suggestion — additional to toolboxes) ═══
  { category: "Saddle Boxes", brand: "Weather Guard", series: "Saddle Box Full Standard 71\"", partNumber: "127-0-02", cost: 752, mapPrice: 770, retailPrice: 1052, sellPrice: 800, installHours: 1.0, source: "eTristate", notes: "Full-size, steel, white", imageUrl: "https://www.weatherguard.com/getattachment/Products/Tool-Boxes/Truck-Tool-Boxes/Saddle-Box/127-0-02.png", sortOrder: 1 },
  { category: "Saddle Boxes", brand: "UWS", series: "69\" Saddle Box (Bright Alum)", partNumber: "TBS-69-BLK", cost: 390, mapPrice: 650, retailPrice: 720, sellPrice: 675, installHours: 1.0, source: "eTristate", notes: "Extra wide, gloss black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQySoyyqLvVr96WTiKTZs9Fg3tU_vMug3WFhI2qUGT1hmORo4dupxdFASnN&s", sortOrder: 2 },
  { category: "Saddle Boxes", brand: "Dee Zee", series: "Red Label Saddle Box 71\"", partNumber: "DZ8170S", cost: 400, mapPrice: undefined, retailPrice: 870, sellPrice: 650, installHours: 1.0, source: "Web", notes: "Brite-Tread aluminum", imageUrl: "https://encrypted-tbn2.gstatic.com/shopping?q=tbn:ANd9GcQcfrLzv0h_OoHoOa7wrvrzB__QChck6RiVR3AEa2-tGZzzcVaYsoaiiEdT-e6vH_tqeOxkur2PvUSSAIs1UG01wcVI7l5OcJUFHbaJtWlEtONp50Rnelx9RncNr26_Brk2TtGSS3Y&usqp=CAc", sortOrder: 3 },

  // ═══ TRANSFER TANKS ═══
  { category: "Transfer Tanks", brand: "Dee Zee", series: "40 gal Steel Rectangle", partNumber: "DZ91752S", cost: 283, mapPrice: undefined, retailPrice: 667, sellPrice: 500, installHours: 2.5, source: "eTristate", notes: "White steel", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSh_N1fGT6H16OtEH021554I0Z5emkhQZhhSAZmbs9rMRpsIwZTecUMay5&s", sortOrder: 1 },
  { category: "Transfer Tanks", brand: "UWS", series: "100 gal L-Shape Hammerhead", partNumber: "TT-100HH", cost: 873, mapPrice: 1015, retailPrice: 1496, sellPrice: 1100, installHours: 2.5, source: "eTristate", notes: "Bright aluminum", imageUrl: "https://www.uwsta.com/media/catalog/product/t/t/tt-100-hh_bright.jpg", sortOrder: 2 },
  { category: "Transfer Tanks", brand: "UWS", series: "100 gal Hammerhead (Black)", partNumber: "TT-100HH-B", cost: 970, mapPrice: 1128, retailPrice: 1662, sellPrice: 1200, installHours: 2.5, source: "eTristate", notes: "Gloss black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSh_N1fGT6H16OtEH021554I0Z5emkhQZhhSAZmbs9rMRpsIwZTecUMay5&s", sortOrder: 3 },
  { category: "Transfer Tanks", brand: "UWS", series: "100 gal L-Shape (Black)", partNumber: "TT-100-L-T-P-B", cost: 970, mapPrice: 1510, retailPrice: 1662, sellPrice: 1500, installHours: 2.5, source: "eTristate", notes: "Gloss black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRSh_N1fGT6H16OtEH021554I0Z5emkhQZhhSAZmbs9rMRpsIwZTecUMay5&s", sortOrder: 4 },
  // BCI Fuel Tanks (dealer pricing TBD)
  { category: "Transfer Tanks", brand: "BCI", series: "FT50 — 50 Gallon", partNumber: "BCI-FT50", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. 55×14×16\". Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_60acabfa98944258996dbd6af26a0c9b~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FT50.jpg", sortOrder: 5 },
  { category: "Transfer Tanks", brand: "BCI", series: "FT100 — 100 Gallon", partNumber: "BCI-FT100", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. 48×23×28\". Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_d5abe08fbfbf4fdc982d9e4b29f00ed3~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FT100.jpg", sortOrder: 6 },

  // ═══ TANK / TOOLBOX COMBOS ═══
  { category: "Tank/Toolbox Combos", brand: "Dee Zee", series: "50 gal Combo (Black Steel)", partNumber: "DZ91740SB", cost: 978, mapPrice: undefined, retailPrice: 2189, sellPrice: 1750, installHours: 2.5, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBR3McjX-3Kdqhd9n3CH-U8IOb1m7p3u0Cw0KPzGO9ae2Cl2tWNBIYqaow&s", sortOrder: 1 },
  { category: "Tank/Toolbox Combos", brand: "UWS", series: "100 gal Combo (Bright Alum)", partNumber: "TT-100-COMBO", cost: 1019, mapPrice: 1585, retailPrice: 1744, sellPrice: 1600, installHours: 2.5, source: "eTristate", notes: undefined, imageUrl: "https://www.uwsta.com/media/catalog/product/t/t/tt-100-combo_bright.jpg", sortOrder: 2 },
  { category: "Tank/Toolbox Combos", brand: "UWS", series: "100 gal Combo (Gloss Black)", partNumber: "TT-100-CB-B", cost: 1136, mapPrice: 1768, retailPrice: 1946, sellPrice: 1800, installHours: 2.5, source: "eTristate", notes: undefined, imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBR3McjX-3Kdqhd9n3CH-U8IOb1m7p3u0Cw0KPzGO9ae2Cl2tWNBIYqaow&s", sortOrder: 3 },
  // BCI Combo Series (dealer pricing TBD)
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB50-10 — 50 gal + 10\" Toolbox", partNumber: "BCI-FTB50-10", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. 60×27×22\". Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 4 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB70-10 — 70 gal + 10\" Toolbox", partNumber: "BCI-FTB70-10", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 5 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB70-10M — 70 gal + 10\" Toolbox (Modified)", partNumber: "BCI-FTB70-10M", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 6 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB90-10 — 90 gal + 10\" Toolbox", partNumber: "BCI-FTB90-10", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 7 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB100-10 — 100 gal + 10\" Toolbox", partNumber: "BCI-FTB100-10", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 8 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB100-10R — 100 gal + 10\" Toolbox (Reverse)", partNumber: "BCI-FTB100-10R", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_e0b771240f6641c8be55e2b0306ea353~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB.jpg", sortOrder: 9 },
  // BCI L-Shaped Tank Combos
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "LTB80 — 80 gal L-Shape + Toolbox", partNumber: "BCI-LTB80", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, L-shaped tank w/ welded toolbox. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_6078cb311fb4439994f53b0ff428d687~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/LTB80.jpg", sortOrder: 10 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "LTB95 — 95 gal L-Shape + Toolbox", partNumber: "BCI-LTB95", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, L-shaped tank w/ welded toolbox. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_78d8723340af40e6b798ebc0a2b44bfc~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/LTB95.jpg", sortOrder: 11 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "L100-18 — 100 gal L-Shape + 18\" Toolbox", partNumber: "BCI-L100-18", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "12ga steel, L-shaped tank w/ 18\" toolbox. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/96b165_25a0d41f139943fbb2922bcaa7bc02ea~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/L100-18.jpg", sortOrder: 12 },
  // BCI Premium Series
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FTB50-8 V3 — 50 gal Premium", partNumber: "BCI-FTB50-8V3", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "Premium series. 12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/ec016e_4e4138951fdf4a32b79a428dde92acb5~mv2.png/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FTB50-8V3.png", sortOrder: 13 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "DM-50 — 50 gal Premium", partNumber: "BCI-DM50", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "Premium series. 12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_205ffc4a7ce94843be8b82dc3692ba58~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/DM-50.jpg", sortOrder: 14 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FBC35 — 35 gal Fuel Bed Combo", partNumber: "BCI-FBC35", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "Premium series. 12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_69000939acf7470fa8266c672bf00096~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FBC35.jpg", sortOrder: 15 },
  { category: "Tank/Toolbox Combos", brand: "BCI", series: "FBC50 — 50 gal Fuel Bed Combo", partNumber: "BCI-FBC50", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 0, installHours: 2.5, source: "Web", notes: "Premium series. 12ga steel, polyurea coated. Dealer pricing TBD", imageUrl: "https://static.wixstatic.com/media/3c85f8_6ab329024b19485193163f7ddc95e067~mv2.jpg/v1/fill/w_400,h_200,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/FBC50.jpg", sortOrder: 16 },

  // ═══ TRANSFER PUMPS ═══
  { category: "Transfer Pumps", brand: "Fill-Rite", series: "15 GPM w/ Manual Nozzle", partNumber: "FR1210H", cost: 405, mapPrice: 630, retailPrice: 691, sellPrice: 650, installHours: 1.0, source: "eTristate", notes: "12V DC", imageUrl: "https://www.fillrite.com/media/catalog/product/f/r/fr1210h.jpg", sortOrder: 1 },
  { category: "Transfer Pumps", brand: "Fill-Rite", series: "15 GPM w/ Auto Nozzle", partNumber: "FR1210HA", cost: 445, mapPrice: 725, retailPrice: 760, sellPrice: 725, installHours: 1.0, source: "eTristate", notes: "12V DC", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnbK11YknjR16NG2b4Up1F2WU1UUvSbbO4kizIZ7nddYfz7PtlusfnedR&s", sortOrder: 2 },
  { category: "Transfer Pumps", brand: "Fill-Rite", series: "20 GPM w/ Manual Nozzle", partNumber: "FR4210H", cost: 476, mapPrice: 780, retailPrice: 813, sellPrice: 800, installHours: 1.0, source: "eTristate", notes: "12V DC", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnbK11YknjR16NG2b4Up1F2WU1UUvSbbO4kizIZ7nddYfz7PtlusfnedR&s", sortOrder: 3 },
  { category: "Transfer Pumps", brand: "GPI", series: "M-150S 15 GPM", partNumber: "110000-107", cost: 375, mapPrice: 479, retailPrice: 595, sellPrice: 500, installHours: 1.0, source: "eTristate", notes: "12V DC economy model", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnbK11YknjR16NG2b4Up1F2WU1UUvSbbO4kizIZ7nddYfz7PtlusfnedR&s", sortOrder: 4 },
  { category: "Transfer Pumps", brand: "GPI", series: "M-150S-AU 15 GPM Auto", partNumber: "110000-100", cost: 432, mapPrice: 594, retailPrice: 725, sellPrice: 600, installHours: 1.0, source: "eTristate", notes: "12V DC auto nozzle", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRMnbK11YknjR16NG2b4Up1F2WU1UUvSbbO4kizIZ7nddYfz7PtlusfnedR&s", sortOrder: 5 },

  // ═══ WINCHES ═══
  { category: "Winches", brand: "Warn", series: "VR EVO 10-S (10,000 lb)", partNumber: "103253", cost: 760, mapPrice: 1301, retailPrice: 1118, sellPrice: 1300, installHours: 2.0, source: "eTristate", notes: "Synthetic rope, top tier", imageUrl: "https://www.warn.com/media/catalog/product/1/0/103253_vr_evo_10s_3qtr_1.jpg", sortOrder: 1 },
  { category: "Winches", brand: "Superwinch", series: "SX10SR (10,000 lb)", partNumber: "1710201", cost: 728, mapPrice: 917, retailPrice: 1100, sellPrice: 950, installHours: 2.0, source: "eTristate", notes: "Synthetic rope", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQffsXvRWFnleHxdUYmVL8KYoxwMKlTYLao2uqrjVdb4fASSJ6FLtAbWY4G&s", sortOrder: 2 },
  { category: "Winches", brand: "Superwinch", series: "SX12SR (12,000 lb)", partNumber: "1712201", cost: 792, mapPrice: 998, retailPrice: 1198, sellPrice: 1000, installHours: 2.0, source: "eTristate", notes: "Synthetic rope", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQffsXvRWFnleHxdUYmVL8KYoxwMKlTYLao2uqrjVdb4fASSJ6FLtAbWY4G&s", sortOrder: 3 },
  { category: "Winches", brand: "Superwinch", series: "Winch2Go (4,000 lb)", partNumber: "1140222", cost: 591, mapPrice: 539, retailPrice: 647, sellPrice: 600, installHours: 0, source: "eTristate", notes: "Portable, steel rope", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQffsXvRWFnleHxdUYmVL8KYoxwMKlTYLao2uqrjVdb4fASSJ6FLtAbWY4G&s", sortOrder: 4 },

  // ═══ AIR BAGS / AIR SPRINGS (George's suggestion) ═══
  { category: "Air Bags", brand: "Firestone", series: "Ride-Rite (Ford F-250/F-350)", partNumber: "2625", cost: 350, mapPrice: undefined, retailPrice: 634, sellPrice: 575, installHours: 2.0, source: "Web", notes: "2017-2024 F-250/F-350 4WD, no compressor", imageUrl: "https://www.firestoneairide.com/content/dam/fir-airide/product-images/2625.png", sortOrder: 1 },
  { category: "Air Bags", brand: "Firestone", series: "Ride-Rite w/ Compressor", partNumber: "2825", cost: 575, mapPrice: undefined, retailPrice: 1000, sellPrice: 950, installHours: 4.0, source: "Web", notes: "Includes wireless compressor kit", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4l3wy5TxozSCQNgjhNBxkfWKz4YickjYTiEUBNhvOyL3P562Ly_jx6uGG&s", sortOrder: 2 },
  { category: "Air Bags", brand: "Air Lift", series: "LoadLifter 5000 Ultimate (F-250/F-350)", partNumber: "88354", cost: 320, mapPrice: undefined, retailPrice: 555, sellPrice: 525, installHours: 2.0, source: "Web", notes: "2023-2026 F-250/F-350 4WD", imageUrl: "https://www.airliftcompany.com/media/catalog/product/8/8/88354.jpg", sortOrder: 3 },
  { category: "Air Bags", brand: "Air Lift", series: "LoadLifter 5000 w/ WirelessONE", partNumber: "88354-WO", cost: 550, mapPrice: undefined, retailPrice: 950, sellPrice: 900, installHours: 4.0, source: "Web", notes: "Includes wireless compressor", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQRULfbUMcHgHKPxuoMiTZlZJuAUcNo2Zzqw6-sdaeP4wz5fcKMLWEYiDps&s", sortOrder: 4 },

  // ═══ JUMPER CABLES ═══
  { category: "Jumper Cables", brand: "Buyers", series: "28' Booster Cables w/ Quick Connect (600A)", partNumber: "5601025", cost: 100, mapPrice: undefined, retailPrice: 233, sellPrice: 200, installHours: 1.0, source: "Web", notes: "Gray Anderson-style plug, 4 AWG, case included", imageUrl: "https://www.buyersproducts.com/sites/default/files/product-images/5601025_0.png", sortOrder: 1 },
  { category: "Jumper Cables", brand: "Buyers", series: "32.5' Booster Cables w/ Quick Connect (1000A)", partNumber: "5601033", cost: 175, mapPrice: undefined, retailPrice: 306, sellPrice: 300, installHours: 1.0, source: "Web", notes: "Black Anderson-style plug, 2 AWG, heavy-duty diesel", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSCSuAjlgPDPT2cgbdQUGG0YOiButx6lv3vIkiOMVGhmddbo-OAVx1l-4Kv&s", sortOrder: 2 },

  // ═══ FLOOR MATS ═══
  { category: "Floor Mats", brand: "WeatherTech", series: "FloorLiner Front (Black)", partNumber: "4412731", cost: 87, mapPrice: 136, retailPrice: 134, sellPrice: 150, installHours: 0, source: "eTristate", notes: "Vehicle-specific", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBYMA8K3fEw0pS83whFdjNB6ScYWrjibZUTA&s", sortOrder: 1 },
  { category: "Floor Mats", brand: "WeatherTech", series: "FloorLiner Rear (Black)", partNumber: "4412732", cost: 63, mapPrice: 99, retailPrice: 99, sellPrice: 100, installHours: 0, source: "eTristate", notes: "Vehicle-specific", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBYMA8K3fEw0pS83whFdjNB6ScYWrjibZUTA&s", sortOrder: 2 },
  { category: "Floor Mats", brand: "WeatherTech", series: "FloorLiner Set (Front + Rear)", partNumber: "WT-SET-BLK", cost: 150, mapPrice: undefined, retailPrice: 235, sellPrice: 250, installHours: 0, source: "Calculated", notes: "Bundle — front + rear, black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTBYMA8K3fEw0pS83whFdjNB6ScYWrjibZUTA&s", sortOrder: 3 },

  // ═══ BED LINERS ═══
  { category: "Bed Liners", brand: "Local Sub", series: "Spray-In (Flatbed / Service Body)", partNumber: "BL-SPRAY", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 800, installHours: 0, source: "Local", notes: "Subbed out locally, flat rate", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQySoyyqLvVr96WTiKTZs9Fg3tU_vMug3WFhI2qUGT1hmORo4dupxdFASnN&s", sortOrder: 1 },

  // ═══ FIRE EXTINGUISHERS & MOUNTS (Craig confirmed: Buckeye 20 lb) ═══
  { category: "Fire Extinguishers", brand: "Buckeye", series: "20 lb ABC Fire Extinguisher", partNumber: "12120", cost: 95, mapPrice: undefined, retailPrice: 175, sellPrice: 175, installHours: 0.25, source: "Craig", notes: "Buckeye 20 lb — per Craig. Labor 0.25hr per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7IbgR091S-G6FJEoumst3Aae8YOH2JvNcwE2gMy4CAe6tkt2qUC--OCo_&s", sortOrder: 1 },

  // ═══ VISES (Craig confirmed: Wilton #21800) ═══
  { category: "Vises", brand: "Wilton", series: "748A 4-1/2\" Mechanics Vise", partNumber: "21800", cost: 280, mapPrice: undefined, retailPrice: 420, sellPrice: 400, installHours: 1.5, source: "Craig", notes: "Wilton 748A — per Craig. Rack w/ reinforcement 1.0hr + vise install 0.5hr per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT7IbgR091S-G6FJEoumst3Aae8YOH2JvNcwE2gMy4CAe6tkt2qUC--OCo_&s", sortOrder: 1 },

  // ═══ PACK RATS / RAT PACKS (Labor guide: Weather Guard, 2.0 hrs) ═══
  { category: "Rat Packs", brand: "Weather Guard", series: "Pack Rat Drawer Unit (Pickup Bed)", partNumber: "WG-PACKRAT", cost: 450, mapPrice: undefined, retailPrice: 750, sellPrice: 700, installHours: 2.0, source: "Labor Guide", notes: "Weather Guard Pack Rat — from Star Labor Guide. 2.0hr install on pickup bed", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbdkubNC04bYAIc3PWD6sCme5ksZa5AU_BZ0kVWF-ohmkjkNlY9bNHVt1I&s", sortOrder: 1 },
  { category: "Rat Packs", brand: "Weather Guard", series: "Pack Rat Drawer Unit (Service Body)", partNumber: "WG-PACKRAT-SB", cost: 450, mapPrice: undefined, retailPrice: 750, sellPrice: 700, installHours: 2.0, source: "Labor Guide", notes: "Weather Guard Pack Rat — from Star Labor Guide. 2.0hr install on service body", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQbdkubNC04bYAIc3PWD6sCme5ksZa5AU_BZ0kVWF-ohmkjkNlY9bNHVt1I&s", sortOrder: 2 },

  // ═══ CTECH CABINETS / DRAWERS (Craig: TM/Marble DRW+SRW, SD SRW+DRW — from Motility spreadsheet) ═══
  // Drawer Units
  { category: "CTech Cabinets", brand: "CTech", series: "Drawer Unit — SD SRW", partNumber: "303000001", cost: 1250, mapPrice: undefined, retailPrice: 1750, sellPrice: 1750, installHours: 1.5, source: "Craig/Motility", notes: "Norstar SD single rear wheel. 1.5hr per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 1 },
  { category: "CTech Cabinets", brand: "CTech", series: "Drawer Unit — SD Dually", partNumber: "303000002", cost: 1320, mapPrice: undefined, retailPrice: 1850, sellPrice: 1850, installHours: 1.5, source: "Craig/Motility", notes: "Norstar SD dual rear wheel. 1.5hr per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 2 },
  { category: "CTech Cabinets", brand: "CTech", series: "Drawer Unit — SRW New Style", partNumber: "303000025", cost: 1395, mapPrice: undefined, retailPrice: 1951, sellPrice: 1951, installHours: 1.5, source: "Craig/Motility", notes: "New style SRW", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 3 },
  { category: "CTech Cabinets", brand: "CTech", series: "Drawer Unit — DRW New Style SD", partNumber: "303000026", cost: 1570, mapPrice: undefined, retailPrice: 2200, sellPrice: 2200, installHours: 1.5, source: "Craig/Motility", notes: "New style DRW SD", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 4 },
  { category: "CTech Cabinets", brand: "CTech", series: "Shovel Tray Drawer Unit", partNumber: "303000016", cost: 860, mapPrice: undefined, retailPrice: 1200, sellPrice: 1200, installHours: 1.5, source: "Craig/Motility", notes: "Shovel tray drawer unit", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 5 },
  // Front Cabinets
  { category: "CTech Cabinets", brand: "CTech", series: "Front Cabinet — Norstar SD Dually", partNumber: "1402005", cost: 1400, mapPrice: undefined, retailPrice: 1965, sellPrice: 1965, installHours: 1.5, source: "Craig/Motility", notes: "14.5 x 26.82 x 15.5 — Norstar SD Dually front", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 6 },
  { category: "CTech Cabinets", brand: "CTech", series: "Front Cabinet — Norstar SD SRW", partNumber: "1403001", cost: 1070, mapPrice: undefined, retailPrice: 1500, sellPrice: 1500, installHours: 1.5, source: "Craig/Motility", notes: "Norstar SD SRW 1st Front VT (built after 11/12/2024)", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 7 },
  { category: "CTech Cabinets", brand: "CTech", series: "Front Cabinet — Bedrock Marble DRW (TM)", partNumber: "9450978", cost: 1570, mapPrice: undefined, retailPrice: 2199, sellPrice: 2199, installHours: 1.5, source: "Craig/Motility", notes: "86-94\" DRW TB TM — Bedrock Marble front cab. 29-13/16 x 29 x 16-1/2", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 8 },
  { category: "CTech Cabinets", brand: "CTech", series: "2-Drawer — CM TMX 86\" SRW", partNumber: "9450979", cost: 965, mapPrice: undefined, retailPrice: 1351, sellPrice: 1351, installHours: 1.5, source: "Craig/Motility", notes: "CM TMX 86\" SRW 2 drawer", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 9 },
  { category: "CTech Cabinets", brand: "CTech", series: "Front Cabinet — CMG 11094 Gen2 CB/SB", partNumber: "9451358", cost: 1490, mapPrice: undefined, retailPrice: 2090, sellPrice: 2090, installHours: 1.5, source: "Craig/Motility", notes: "CMG 11094 gen2 CB/SB - DEF 1st Front VT", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 10 },
  // Service Body Specific
  { category: "CTech Cabinets", brand: "CTech", series: "SC — SRW Long Bed", partNumber: "303000003", cost: 1680, mapPrice: undefined, retailPrice: 2350, sellPrice: 2350, installHours: 1.5, source: "Craig/Motility", notes: "SRW long bed service compartment", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 11 },
  { category: "CTech Cabinets", brand: "CTech", series: "SC — SRW Long Bed Middle", partNumber: "303000017", cost: 860, mapPrice: undefined, retailPrice: 1200, sellPrice: 1200, installHours: 1.5, source: "Craig/Motility", notes: "SRW long bed middle compartment", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 12 },
  // RKI Body Specific
  { category: "CTech Cabinets", brand: "CTech", series: "RKI T5680/L5680 SRW — Energy Transfer", partNumber: "CFG-24952", cost: 840, mapPrice: undefined, retailPrice: 1174, sellPrice: 1174, installHours: 1.5, source: "Craig/Motility", notes: "Energy Transfer for RKI T5680/L5680 SRW", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 13 },
  { category: "CTech Cabinets", brand: "CTech", series: "RKI 566-57-58 DRW", partNumber: "CFG-25056", cost: 1570, mapPrice: undefined, retailPrice: 2200, sellPrice: 2200, installHours: 1.5, source: "Craig/Motility", notes: "For RKI 566/567/568 DRW bodies", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 14 },
  // ArchRock / Flatrock
  { category: "CTech Cabinets", brand: "CTech", series: "ArchRock Front", partNumber: "510121", cost: 890, mapPrice: undefined, retailPrice: 1250, sellPrice: 1250, installHours: 1.5, source: "Craig/Motility", notes: "20.5 x 29.50 x 12", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 15 },
  { category: "CTech Cabinets", brand: "CTech", series: "ArchRock Rear", partNumber: "CFG-34131", cost: 930, mapPrice: undefined, retailPrice: 1300, sellPrice: 1300, installHours: 1.5, source: "Craig/Motility", notes: "Rear ArchRock unit", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 16 },
  { category: "CTech Cabinets", brand: "CTech", series: "Flatrock — Knapheide 696F", partNumber: "CFG-41216", cost: 980, mapPrice: undefined, retailPrice: 1370, sellPrice: 1370, installHours: 1.5, source: "Craig/Motility", notes: "For Knapheide 696F body", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 17 },
  // Large Cabinet
  { category: "CTech Cabinets", brand: "CTech", series: "Cabinet 25W × 36H × 19D", partNumber: "CT2536", cost: 2310, mapPrice: undefined, retailPrice: 3230, sellPrice: 3230, installHours: 2.0, source: "Craig/Motility", notes: "Large cabinet — 25 x 36 x 19", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRGtOBvhkfSQoaGVt1gEah6FsDmxCCtm4DdIFgiuWsJWY0ZlFqckF78S3cN&s", sortOrder: 18 },
  // Dividers (accessory)
  { category: "CTech Cabinets", brand: "CTech", series: "Dividers — Side to Side", partNumber: "D355", cost: 36, mapPrice: undefined, retailPrice: 50, sellPrice: 50, installHours: 0, source: "Craig/Motility", notes: "Drawer dividers", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR3mAr3Oquxk22udSTbEMyIdUKadbt2uZz1wYyXVEmWA06nMwVjkbKCHizQ&s", sortOrder: 19 },

  // ═══ CABINET LIGHTING (Craig confirmed: Buyers LED strips) ═══
  { category: "Cabinet Lighting", brand: "Buyers", series: "36\" LED Interior Light Strip", partNumber: "5623755", cost: 55, mapPrice: undefined, retailPrice: 110, sellPrice: 100, installHours: 1.0, source: "Craig", notes: "Buyers 36\" LED — per Craig. 1hr per side per labor guide", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT_IHErKVGTVquJk-c_5EwcUuhc_IGa3uttw6r_zwGT1BBn9e-czdqGu4O_9Tqy7YKsX1iLY7MApTwtDenW-ZIfSdzGIrUpkqT3MB1X6YnoJfxp0N1M08pi8IoVyVWPMflFVUJzXkU&usqp=CAc", sortOrder: 1 },
  { category: "Cabinet Lighting", brand: "Buyers", series: "24\" LED Interior Light Strip", partNumber: "5622537", cost: 40, mapPrice: undefined, retailPrice: 80, sellPrice: 75, installHours: 1.0, source: "Craig", notes: "Buyers 24\" LED — per Craig. 1hr per side per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/shopping?q=tbn:ANd9GcREfM6Q5UXuffasJpELR76lLHgaMmpOl2j-yo0v2YLcVH_8B9xSbHoNyiEYAdvAccWuomx0HtZ7k6y3QJxp97jdsF99FiTvsVab6pDjzuoiMuS1euGRlQbt6PFjYN8Gnw&usqp=CAc", sortOrder: 2 },
  { category: "Cabinet Lighting", brand: "Buyers", series: "Full Compartment Light Kit (both sides)", partNumber: "CL-FULL-KIT", cost: 0, mapPrice: undefined, retailPrice: undefined, sellPrice: 900, installHours: 6.0, source: "Labor Guide", notes: "Full LED strip package — down one side of each compartment + across top. 6.0hr per labor guide", imageUrl: "https://encrypted-tbn1.gstatic.com/shopping?q=tbn:ANd9GcT_IHErKVGTVquJk-c_5EwcUuhc_IGa3uttw6r_zwGT1BBn9e-czdqGu4O_9Tqy7YKsX1iLY7MApTwtDenW-ZIfSdzGIrUpkqT3MB1X6YnoJfxp0N1M08pi8IoVyVWPMflFVUJzXkU&usqp=CAc", sortOrder: 3 },

  // ═══ WORK LIGHTS (Labor guide: 1.5hr per set of 2, add brackets 1.0hr) ═══
  { category: "Work Lights", brand: "Buyers", series: "LED Work Light (each)", partNumber: "1492196", cost: 85, mapPrice: undefined, retailPrice: 250, sellPrice: 150, installHours: 1.5, source: "Web", notes: "12V LED, truck/utility mount. 1.5hr per set of 2 per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_fhdCFjTC_QMfjbQH9poBJFYmpAG5k05pJvRTlbPPNJXkwXw0Kh3lEhAN&s", sortOrder: 1 },
  { category: "Work Lights", brand: "Buyers", series: "4-Light Package (2 rack + 2 bed)", partNumber: "WL-PKG-4", cost: 340, mapPrice: undefined, retailPrice: undefined, sellPrice: 600, installHours: 3.0, source: "Labor Guide", notes: "2 on headache rack + 2 on bed. 1.5hr per set × 2 sets per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ_fhdCFjTC_QMfjbQH9poBJFYmpAG5k05pJvRTlbPPNJXkwXw0Kh3lEhAN&s", sortOrder: 2 },

  // ═══ LADDER RACKS (Craig confirmed: Holman + Weather Guard. 4.0hr per labor guide) ═══
  { category: "Ladder Racks", brand: "Weather Guard", series: "1000 lb Capacity Ladder Rack", partNumber: "1225-CM", cost: 1290, mapPrice: undefined, retailPrice: 1800, sellPrice: 1800, installHours: 4.0, source: "Craig/Motility", notes: "Weather Guard 1000 lb capacity. 4.0hr per labor guide", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQo1S85b8YiYci1QtQ-wfeLC4OCdZDQA3LdRB2IbQJc1SRUzfHzoVDs5jFn&s", sortOrder: 1 },
  { category: "Ladder Racks", brand: "Holman", series: "Standard Cab 8ft Bed Ladder Rack", partNumber: "2FCS8C", cost: 2070, mapPrice: undefined, retailPrice: 2900, sellPrice: 2900, installHours: 4.0, source: "Craig/Motility", notes: "Holman — standard cab, 8ft bed. Truck specific", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg2WgcD7xz1nNuRTsgDwGceoaagSXwXRH6RteGl06FoXp1AMHLh6acr2hR&s", sortOrder: 2 },
  { category: "Ladder Racks", brand: "Holman", series: "Pro Rack — Body Mount Multi-Fit", partNumber: "2SBS8C", cost: 1570, mapPrice: undefined, retailPrice: 2200, sellPrice: 2200, installHours: 4.0, source: "Craig/Motility", notes: "Pro Rack body mount multi-fit pro series", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg2WgcD7xz1nNuRTsgDwGceoaagSXwXRH6RteGl06FoXp1AMHLh6acr2hR&s", sortOrder: 3 },
  { category: "Ladder Racks", brand: "Holman", series: "Pro Rack — Service Body Ext Cab 8ft", partNumber: "2SBS8E", cost: 1215, mapPrice: undefined, retailPrice: 1700, sellPrice: 1700, installHours: 4.0, source: "Craig/Motility", notes: "Pro Rack Leg/Bars Kit, Service Body, Ext Cab, Black", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg2WgcD7xz1nNuRTsgDwGceoaagSXwXRH6RteGl06FoXp1AMHLh6acr2hR&s", sortOrder: 4 },
  { category: "Ladder Racks", brand: "Holman", series: "Service Body Reg Cab 8ft", partNumber: "2SBS8R", cost: 1570, mapPrice: undefined, retailPrice: 2200, sellPrice: 2200, installHours: 4.0, source: "Craig/Motility", notes: "Holman service body, reg cab, 8ft", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTg2WgcD7xz1nNuRTsgDwGceoaagSXwXRH6RteGl06FoXp1AMHLh6acr2hR&s", sortOrder: 5 },
  { category: "Ladder Racks", brand: "Star Custom", series: "Side Mount Ladder Rack", partNumber: "SLR", cost: 500, mapPrice: undefined, retailPrice: 700, sellPrice: 700, installHours: 4.0, source: "Craig/Motility", notes: "Star custom side mount rack", imageUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQZ_2xZ5vYPTGqTNhLBThihzFqvIwgFDwVZLe9TzkbeW1Yb3qGFj7irlvx6&s", sortOrder: 6 },
];

export const seedAccessories = internalMutation({
  args: {},
  returns: v.null(),
  handler: async (ctx) => {
    // Clear existing accessories
    const existing = await ctx.db.query("accessories").collect();
    for (const item of existing) {
      await ctx.db.delete(item._id);
    }

    // Insert all accessories
    for (const item of ACCESSORIES) {
      await ctx.db.insert("accessories", {
        category: item.category,
        brand: item.brand,
        series: item.series,
        partNumber: item.partNumber,
        cost: item.cost,
        mapPrice: item.mapPrice,
        retailPrice: item.retailPrice,
        sellPrice: item.sellPrice,
        installHours: item.installHours,
        source: item.source,
        notes: item.notes,
        imageUrl: item.imageUrl,
        sortOrder: item.sortOrder,
      });
    }

    // Set labor rate to $150/hr (Jon confirmed)
    const existingRate = await ctx.db.query("settings").withIndex("by_key", q => q.eq("key", "laborRate")).unique();
    if (existingRate) {
      await ctx.db.patch(existingRate._id, { value: "150" });
    } else {
      await ctx.db.insert("settings", { key: "laborRate", value: "150" });
    }

    // Set default markup to 40% (Jon confirmed)
    const existingMarkup = await ctx.db.query("settings").withIndex("by_key", q => q.eq("key", "defaultMarkupPercent")).unique();
    if (existingMarkup) {
      await ctx.db.patch(existingMarkup._id, { value: "40" });
    } else {
      await ctx.db.insert("settings", { key: "defaultMarkupPercent", value: "40" });
    }

    return null;
  },
});
